version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      time: "10:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
