repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]

  - repo: local
    hooks:
      - id: go-version
        name: go version
        entry: scripts/check-go-version
        language: script
        types:
          - go

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_validate

  - repo: git://github.com/golangci/golangci-lint
    rev: v1.41.1
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: gomod
        name: gomod
        entry: scripts/pre-commit-go-mod
        language: script
        files: go.mod
        pass_filenames: false
